INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (382, 'ÕŒ¬Œ»À-œ/—»Õ“  5Î', NULL, 1, NULL, NULL, 2, 1, 1, 5, 10, 1, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (384, 'Ã¿—ÀŒ', NULL, 1, NULL, NULL, 3, 3, 1, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (385, 'À” Œ…À — 10w30 (5Î', NULL, 1, NULL, NULL, 2, 1, 1, 6, 5, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (386, 'À” Œ…À — 15w40 (1Î', NULL, 1, NULL, NULL, 2, 1, 4, 9, 5, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (392, 'Ã8‚    (4Î)', NULL, 2, NULL, NULL, 2, 1, 2, 3, 8, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (400, 'ƒŒ“-4  (910 „ )', NULL, 2, NULL, NULL, 3, 1, 4, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (402, 'À” Œ…À —”œ≈–  5Î', NULL, 2, NULL, NULL, 2, 1, 1, 5, 10, 3, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (405, 'À” Œ…À —“¿Õƒ¿–“ 1Î', NULL, 2, NULL, NULL, 2, 1, 4, 6, 12, 1, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (407, 'ƒŒ“-4       0.25 À', NULL, 1, NULL, NULL, 3, 1, 5, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (408, '¿-80  (10À)', NULL, 1, NULL, NULL, 9, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (409, '¿-80  (20À)', NULL, 1, NULL, NULL, 9, 1, 2, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (412, 'ƒ“  (10À)', NULL, 1, NULL, NULL, 9, 1, 1, 3, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (413, 'ƒ“  (20À)', NULL, 1, NULL, NULL, 9, 1, 2, 3, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (414, '¿»-92  (10À)', NULL, 1, NULL, NULL, 9, 1, 1, 4, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (415, '¿»-92  (20À)', NULL, 1, NULL, NULL, 9, 1, 2, 4, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (416, '¿»-95  (10À)', NULL, 1, NULL, NULL, 9, 1, 1, 5, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (420, 'ÕŒ¬Œ…À-— 80/90 (1À', NULL, 1, NULL, NULL, 2, 3, 4, 2, 7, 2, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (421, 'ÕŒ¬Œ…À-— 80/90 (3À', NULL, 1, NULL, NULL, 2, 3, 8, 2, 7, 2, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (422, 'ÕŒ¬Œ…À-Ã 15/40 (1À', NULL, 1, NULL, NULL, 2, 1, 4, 9, 10, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (423, 'ÕŒ¬Œ…À-Ã 15/30 (5À', NULL, 1, NULL, NULL, 2, 1, 1, 14, 10, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (425, 'À»“ŒÀ  0.35 Î', NULL, 1, NULL, NULL, 2, 4, 2, 2, 6, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (427, ' ¿–“¿ — »ƒŒ ', NULL, 1, NULL, NULL, 8, 1, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (428, 'ÕŒ¬Œ…À ›2 10W30 (1', NULL, 1, NULL, NULL, 2, 1, 4, 6, 11, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (429, 'ÕŒ¬Œ…À-Ã 15/40 (5À', NULL, 1, NULL, NULL, 2, 1, 1, 9, 10, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (436, 'À” Œ…À-—” 10W40 4Î', NULL, 1, NULL, NULL, 2, 1, 2, 7, 5, 1, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (437, 'À” Œ…À-—” 10W40 1Î', NULL, 1, NULL, NULL, 2, 1, 4, 7, 5, 1, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (438, 'À” Œ…À œ–ŒÃ€¬  4Î', NULL, 1, NULL, NULL, 2, 1, 2, 20, 5, 1, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (439, 'ÕŒ¬Œ…À SAE 5W40 5Î', NULL, 1, NULL, NULL, 2, 1, 1, 5, 10, 3, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (440, '“Œ—ŒÀ ƒÁÂÊ   5Î', NULL, 1, NULL, NULL, 3, 2, 2, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (443, 'Ã¿—ÀŒ œ–ŒÃ€¬   4Î', NULL, 2, NULL, NULL, 2, 1, 2, 18, 15, 4, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (444, 'Ã10√2   (4Î)', NULL, 2, NULL, NULL, 2, 1, 2, 13, 11, 2, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (446, 'Ã8¬    (4Î)', NULL, 2, NULL, NULL, 2, 1, 2, 3, 11, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (447, 'À” Œ…À “Ã4  (4À)', NULL, 2, NULL, NULL, 2, 3, 2, 2, 5, 2, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (448, 'ÕŒ¬Œ…À —”œ≈–-“  5À', NULL, 2, NULL, NULL, 2, 3, 1, 2, 7, 2, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (450, 'ÕŒ¬Œ…À SAE15W40 1À', NULL, 2, NULL, NULL, 2, 1, 4, 9, 10, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (451, '–Œ—¿ ƒ-4', NULL, 2, NULL, NULL, 3, 1, 6, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (452, 'À” Œ…À — 10W40 5Î', NULL, 2, NULL, NULL, 2, 1, 1, 7, 5, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (453, 'À” Œ…À — 10W40 4À', NULL, 2, NULL, NULL, 2, 1, 2, 7, 15, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (455, ' -“¿ ŒœÀ¿“€ ¡»À¿…Õ', NULL, 2, NULL, NULL, 8, 9, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (456, ' ¿–“¿ ¡»À¿…Õ  300', NULL, 2, NULL, NULL, 8, 10, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (457, 'Ã¿—ÀŒ Ãœ“-2Ã  (5À)', NULL, 2, NULL, NULL, 2, 1, 1, 20, 16, 4, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (458, 'À” Œ…À ¿¬“Œ  4Î', NULL, 2, NULL, NULL, 2, 1, 2, 20, 15, 4, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (460, '›   À¿—— 10/40  1À', NULL, 2, NULL, NULL, 2, 1, 4, 7, 10, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (461, '›   À¿—— 10/40  4À', NULL, 2, NULL, NULL, 2, 1, 2, 7, 10, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (462, '›   À¿—— 10/40  5À', NULL, 2, NULL, NULL, 2, 1, 1, 7, 10, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (463, '›  —“¿Õƒ 10/30 1À', NULL, 2, NULL, NULL, 2, 1, 4, 6, 10, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (464, '›  —“¿Õƒ 10/30 4À', NULL, 2, NULL, NULL, 2, 1, 2, 6, 10, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (465, '›  —“¿Õƒ 10/30 5À', NULL, 2, NULL, NULL, 2, 1, 1, 6, 10, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (466, '›  —“¿Õƒ 10/40 4À', NULL, 2, NULL, NULL, 2, 1, 4, 7, 10, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (467, '›  —“¿Õƒ 10/40 5À', NULL, 2, NULL, NULL, 2, 1, 1, 7, 10, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (468, '›  —”œ≈– 10/30 1À', NULL, 2, NULL, NULL, 2, 1, 4, 6, 10, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (469, '›  —”œ≈– 10/30 4À', NULL, 2, NULL, NULL, 2, 1, 2, 6, 10, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (470, 'ÕŒ¬Œ…À › 2      5À', NULL, 2, NULL, NULL, 2, 1, 1, 6, 10, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (473, 'À” Œ…À “Ã (4Î)', NULL, 2, NULL, NULL, 2, 3, 2, 2, 5, 2, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (474, 'Ã8‚    (3Î)', NULL, 2, NULL, NULL, 2, 1, 8, 3, 4, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (475, '—»Õ“≈« —”œ≈–   5Î', NULL, 2, NULL, NULL, 2, 1, 1, 5, 17, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (476, 'Ã10„2     ( 3Î)', NULL, 2, NULL, NULL, 2, 1, 8, 4, 5, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (477, 'ESSO ATF      1Î', NULL, 2, NULL, NULL, 2, 3, 4, 7, 2, 1, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (478, 'U-tech navigator 1', NULL, 2, NULL, NULL, 2, 1, 4, 5, 18, 1, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (492, ' ¿–“¿ Ã“—  160', NULL, 2, NULL, NULL, 8, 11, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (493, ' ¿–“¿ Ã“—   320', NULL, 2, NULL, NULL, 8, 12, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (501, 'U-tech C 10w40 5Î', NULL, 2, NULL, NULL, 2, 1, 1, 7, 19, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (502, 'U-tech N 10w30 1Î', NULL, 2, NULL, NULL, 2, 1, 4, 6, 19, 1, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (503, 'U-tech N 15w40 5Î', NULL, 2, NULL, NULL, 2, 1, 1, 9, 19, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (530, '—œ≈ “–ŒÀ  (4À)', NULL, 2, NULL, NULL, 2, 1, 2, 5, 7, 1, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (531, 'À»“ŒÀ  (40Í„)', NULL, 2, NULL, NULL, 2, 4, 7, 1, 4, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (532, '“Õ  5W40  (4À)', NULL, 2, NULL, NULL, 2, 1, 2, 5, 4, 1, 2);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (533, '“Õ  SAE 15W40 (5À)', NULL, 2, NULL, NULL, 2, 1, 1, 9, 8, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (534, 'À” Œ…À —“ 10W40 1À', NULL, 2, NULL, NULL, 2, 1, 4, 7, 5, 3, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (535, 'À” Œ…À —”œ 10W40 5', NULL, 2, NULL, NULL, 2, 1, 1, 7, 5, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (536, '”ÒÎÛ„Ë Ò‚ˇÁË', NULL, 2, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (537, 'Ã6Á14√', NULL, 2, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (538, 'ƒŒ“4 “Œ–—¿', NULL, 2, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (539, 'Ã√-15-¬', NULL, 2, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (540, 'Õ≈¬¿ ƒŒ“-3 (0,5Î)', NULL, 2, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (541, '“Õ  —”œ≈–', NULL, 2, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (542, '“Õ  10W40', NULL, 2, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (543, 'À»“ŒÀ (30Í„)', NULL, 2, NULL, NULL, 2, 4, 7, 1, 4, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (544, '= ¿» - 95 =', NULL, 1, NULL, NULL, 7, 7, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (545, '= ¿» - 92 =', NULL, 1, NULL, NULL, 7, 8, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (546, '= ¿ - 80 =', NULL, 1, NULL, NULL, 7, 9, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (547, '= ƒ“ =', NULL, 1, NULL, NULL, 7, 10, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (548, 'ƒ“  (30Î)', NULL, 1, NULL, NULL, 9, 1, 2, 3, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (549, '¬Ã√« (30Î)', NULL, 1, NULL, NULL, 2, 5, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (555, 'À»“ŒÀ 18  √', NULL, 1, NULL, NULL, 2, 4, 8, 2, 1, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (556, 'ÍËÔË˜ Ï‡Í‡ Ã-150', NULL, -1, NULL, NULL, 6, 2, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (557, '”ÒÎÛ„Ë —“Œ', NULL, 500, NULL, NULL, 7, 5, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (558, 'ZIK 5000 5W30 4Î', NULL, 1, NULL, NULL, 2, 1, 2, 8, 23, 2, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (559, 'Ã8√2   5À', NULL, 1, NULL, NULL, 2, 1, 1, 1, 19, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (560, 'Ã8√2   10À', NULL, 1, NULL, NULL, 2, 1, 6, 3, 19, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (561, 'Ã8-ƒÏ  10 À', NULL, 1, NULL, NULL, 2, 1, 6, 3, 19, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (562, 'Ã10 ƒÏ  10À', NULL, 1, NULL, NULL, 2, 1, 6, 4, 19, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (563, 'SINTOIL —“  1À', NULL, 1, NULL, NULL, 2, 1, 4, 7, 17, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (564, 'SINTOIL —“ 5À', NULL, 1, NULL, NULL, 2, 1, 1, 7, 17, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (565, 'SINTOIL —”œ≈– 1À', NULL, 1, NULL, NULL, 2, 1, 4, 7, 17, 3, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (570, '¡ÂÌ 0.5', NULL, 10, NULL, NULL, 5, 1, 2, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (566, 'SINTOIL —”œ≈–  5À', NULL, 1, NULL, NULL, 2, 1, 1, 7, 17, 3, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (567, 'SINTOIL ATF  1À', NULL, 1, NULL, NULL, 2, 3, 4, 7, 7, 1, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (571, '¡ÓÌ‡Í‚‡ 0,25', NULL, 10, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (572, '¡ÓÌ‡Í‚‡ 0,5', NULL, 10, NULL, NULL, 5, 1, 2, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (573, '¡ÓÌ‡Í‚‡ ¬Ë‚‡ 0,5 Ô', NULL, 10, NULL, NULL, 5, 1, 2, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (574, '¡ÓÌ‡Í‚‡ 1 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 3, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (575, '¡ÓÌ‡Í‚‡ ¬Ë‚‡ 1 Î Ô', NULL, 10, NULL, NULL, 5, 1, 2, 3, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (576, '¡ÓÌ‡Í‚‡ 2 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 6, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (577, ' ÓÍ‡-ÍÓÎ‡ 0,25', NULL, 10, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (578, ' ÓÍ‡-ÍÓÎ‡ 0,5 Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (579, ' ÓÍ‡-ÍÓÎ‡ 1 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 3, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (608, '¡ÂÌ 0,33', NULL, 10, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (580, ' ÓÍ‡-ÍÓÎ‡ 1,5 Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 4, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (581, ' ÓÍ‡-ÍÓÎ‡ 2 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 6, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (582, 'œ‡ÛÂÈ‰ 0,5 Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (583, '—Ô‡ÈÚ 0,25', NULL, 10, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (584, '—Ô‡ÈÚ 0,5 Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (585, '—Ô‡ÈÚ 1 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 3, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (586, '—Ô‡ÈÚ 1,5 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 4, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (587, '—Ô‡ÈÚ 2 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 6, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (588, '‘‡ÌÚ‡ 0,25', NULL, 10, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (589, '‘‡ÌÚ‡ 0,5 Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (590, '‘‡ÌÚ‡ 1 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 3, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (591, '‘‡ÌÚ‡ 1.5 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 4, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (592, '‘‡ÌÚ‡ 2 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 6, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (609, ' ÓÍ‡-ÍÓÎ‡ 0,33', NULL, 1, NULL, NULL, 5, 1, 1, 7, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (610, '‘‡ÌÚ‡ 0,33', NULL, 1, NULL, NULL, 5, 1, 1, 7, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (593, '◊‡È 0,5 Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (594, '◊‡È 1 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 3, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (595, '◊‡È 1.5 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 4, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (611, '—Ô‡ÈÚ 0,33', NULL, 1, NULL, NULL, 5, 1, 1, 7, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (596, '◊‡È 1.75 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 5, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (597, 'ÿ‚ÂÔÒ 0,25', NULL, 10, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (598, 'ÿ‚ÂÔÒ 0,5 Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (599, 'ÿ‚ÂÔÒ 1 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 3, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (600, 'ÿ‚ÂÔÒ 2 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 6, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (601, 'ÿ‚ÂÔÒ 1.5 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 4, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (602, '◊‡È ¬ËÚ‡Ó 0,5 Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (603, '◊‡È ¬ËÚ‡Ó 1 Î Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 3, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (604, '◊‡È ¬ËÚ‡Ó 1.75 Ô˝Ú', NULL, 10, NULL, NULL, 5, 1, 2, 5, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (605, ' ÛÊÍ‡ Ë ¡Ó˜Í‡ 0.5', NULL, 10, NULL, NULL, 5, 3, 2, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (606, ' ÛÊÍ‡ Ë ¡Ó˜Í‡ 1.5', NULL, 10, NULL, NULL, 5, 3, 2, 4, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (607, '√Î‡‰Ë‡ÚÓ 0.5 Î', NULL, 10, NULL, NULL, 5, 2, 1, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (612, '—ÓÍ ƒÓ·˚È 0,45', NULL, 1, NULL, NULL, 5, 1, 1, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (613, '—ÓÍ ƒÓ·˚È 0,9', NULL, 1, NULL, NULL, 5, 1, 1, 3, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (614, '¿‰ÂÌ‡ÎËÌ –‡¯ 0,25', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (615, '¿‰ÂÌ‡ÎËÌ –‡¯ 0,5', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (616, '¿Í‚‡ ÃËÌ „‡ÁË 0,6', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (617, '¿Í‚‡ ÃËÌ Ì/„‡Á 0,6', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (618, '◊‡È ÀËÔÚÓÌ 0,6', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (619, 'ÃËËÌ‰‡ 0,6', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (620, 'œÂÔÒË 0,6', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (621, '—Â‚ÂÌ ¿Ô 0,6', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (622, '◊‡È ÀËÔÚÓÌ 1,25', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (623, '—ÓÍ ‘ÛÍÚ—‡‰ 0,385', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (624, '—ÓÍ ‘ÛÍÚ—‡‰ 0,485', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (625, '—ÓÍ ‘ÛÍÚ—‡‰ 0,95', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (626, 'ÃËËÌ‰‡ 0,33 Ê/·', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (627, 'ÀËÔÚÓÌ 0,33 Ê/·', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (628, 'œÂÔÒË 0,33 Ê/·', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (629, '—Â‚ÂÌ ¿Ô 0,33 Ê/·', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (630, '¿Í‚‡ ¿ÍÚË‚ 0,6', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (631, '¿Í‚‡ ÃËÌ „‡Á 1,25', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (632, '¿Í‚‡ ÃËÌ Ì/„ 1,25', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (633, 'œÂÔÒË 1,25', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (634, '—Â‚ÂÌ ¿Ô 1,25', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (635, '¿Í‚‡ ¿ÍÚË‚ 1,25', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (636, '—ÓÍ ‘ÛÍÚ—‡‰ 0,2', NULL, 1, NULL, NULL, 5, 1, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (637, 'Sintec Œ∆-40 10 Í„', NULL, 1, NULL, NULL, 3, 2, 3, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (638, 'Sintec Œ∆-40 1 Í„', NULL, 1, NULL, NULL, 3, 2, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (639, 'Sintec Œ∆-40 20 Í„', NULL, 1, NULL, NULL, 3, 2, 6, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (640, 'Sintec Œ∆-40 5 Í„', NULL, 1, NULL, NULL, 3, 2, 2, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (641, 'Sintec Œ∆-65 1 Í„', NULL, 1, NULL, NULL, 3, 2, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (642, 'Sintec Euro40 1Í„', NULL, 1, NULL, NULL, 3, 2, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (643, 'Sintec Euro40 10Í„', NULL, 1, NULL, NULL, 3, 2, 3, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (644, 'Sintec Euro40 5Í„', NULL, 1, NULL, NULL, 3, 2, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (645, 'Sintec Ultra45 1Í„', NULL, 1, NULL, NULL, 3, 2, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (646, 'Sintec Ultr45 10Í„', NULL, 1, NULL, NULL, 3, 2, 3, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (647, 'Sintec Ultra45 5Í„', NULL, 1, NULL, NULL, 3, 2, 2, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (648, 'SIBIRIA G-12 1Í„', NULL, 1, NULL, NULL, 3, 2, 1, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (649, 'SIBIRIA G-12 5Í„', NULL, 1, NULL, NULL, 3, 2, 2, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (650, '◊ËÒÚÓ œÎ˛Ò ÁËÏ‡ 4Î', NULL, 1, NULL, NULL, 3, 2, 2, 1, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (651, 'SIBIRIA ÓÏ˚‚.ÒÚÂÍ.', NULL, 1, NULL, NULL, 3, 5, 3, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (652, ' ‚‡Ò –ÛÒ/‰‡ 0,5', NULL, 10, NULL, NULL, 5, 3, 2, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (653, 'Ã‡ÛÌÚË ƒ¸˛ 0,5', NULL, 10, NULL, NULL, 5, 1, 1, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (654, '—ÓÍ ƒÓ·˚È 0,33', NULL, 10, NULL, NULL, 5, 1, 1, 7, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (655, '—ÓÍ ƒÓ·˚È 1Î', NULL, 1, NULL, NULL, 5, 1, 2, 3, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (10, '¿»-92  4', NULL, 200, NULL, NULL, 1, 1, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (11, '¿»-80  4', NULL, 200, NULL, NULL, 1, 9, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (12, 'ƒ“   4', NULL, 300, NULL, NULL, 1, 4, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (550, 'À»“ŒÀ 21', NULL, 0, NULL, NULL, 2, 4, 8, 2, 4, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (14, '¿»-96  4', NULL, 50, NULL, NULL, 1, 7, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (15, '¿»-95  4', NULL, 100, NULL, NULL, 1, 6, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (239, 'Ã 5 « 12/√ 4.5À', NULL, 1, NULL, NULL, 2, 1, 7, 1, 9, 2, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (551, 'ZIK C-4 10W40', NULL, 1, NULL, NULL, 2, 1, 13, 7, 23, 2, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (18, '¿»-98  4', NULL, 150, NULL, NULL, 1, 8, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (552, '¬Ã√« (20Î)', NULL, 1, NULL, NULL, 2, 5, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (553, '¬Ã√« (10Î)', NULL, 1, NULL, NULL, 2, 5, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (50, '¿¬“ŒÀ', NULL, 5, NULL, NULL, 2, 1, 1, 3, 4, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (51, 'À»“ŒÀ', NULL, 100, NULL, NULL, 2, 4, 2, 2, 4, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (52, '“Œ—ŒÀ', NULL, 10, NULL, NULL, 3, 2, 1, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (53, 'ƒÃ', NULL, 10, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (54, 'Ã10«12', NULL, 10, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (55, 'Ã8¬    (2.5À)', NULL, 10, NULL, NULL, 2, 1, 3, 3, 4, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (554, 'ZIC SD 5000 CF4', NULL, 1, NULL, NULL, 2, 1, 14, 9, 23, 1, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (61, '“¿ƒ-17', NULL, 10, NULL, NULL, 2, 3, 4, 1, 4, 2, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (65, '–Œ—¿  0,5Î', NULL, 5, NULL, NULL, 3, 1, 1, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (100, '“ŒÃ‹', NULL, 5, NULL, NULL, 3, 1, 1, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (109, '›À≈ “–ŒÀ»“ 1À ƒ/¿ ', NULL, 2, NULL, NULL, 3, 4, 1, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (167, 'Õ≈¬¿  0,5Î', NULL, 1, NULL, NULL, 3, 1, 1, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (172, '“Œ—ŒÀ  10 Î', NULL, 1, NULL, NULL, 3, 2, 3, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (173, '“Œ—ŒÀ  5 Î', NULL, 1, NULL, NULL, 3, 2, 2, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (174, '“Œ—ŒÀ  Õ– 5À', NULL, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (175, 'Ã¿—ÀŒ Ã6Ã5 5À', NULL, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (176, 'Ã¿—ÀŒ Ã6   2,5À', NULL, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (177, 'Ã¿—ÀŒ œ–ŒÃ€¬  4.7À', NULL, 1, NULL, NULL, 2, 1, 12, 18, 12, 4, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (183, 'Ã10√2    (5À)', NULL, 1, NULL, NULL, 2, 1, 1, 4, 4, 2, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (221, 'Ã6Á12√   (5À)', NULL, 1, NULL, NULL, 2, 1, 1, 2, 4, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (222, 'Ã5Á12√   (5À)', NULL, 1, NULL, NULL, 2, 1, 1, 1, 4, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (223, '“Ã5-18  3À', NULL, 1, NULL, NULL, 2, 3, 8, 1, 4, 2, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (236, '“¿ƒ17  (3À)', NULL, 1, NULL, NULL, 2, 3, 8, 1, 4, 2, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (237, 'Ã5Á/12√  (1À)', NULL, 1, NULL, NULL, 2, 1, 4, 1, 10, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (238, 'Ã8¬    (1À)', NULL, 1, NULL, NULL, 2, 1, 4, 3, 4, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (254, 'Ã8¬ (¿¬“ŒÀ) 5À', NULL, 1, NULL, NULL, 2, 1, 1, 3, 4, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (265, '“Œ—ŒÀ   20 Î', NULL, 1, NULL, NULL, 3, 2, 6, 2, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (266, 'œ–ŒÃ€¬ —œ≈ “–', NULL, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (267, '¿¬“ŒÀ 2,3 À', NULL, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (268, ' ≈–Œ—»Õ', NULL, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (269, '“Œ—ŒÀ  1 Î', NULL, 1, NULL, NULL, 3, 2, 1, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (270, '“¿ƒ17 (2,5À)', NULL, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (271, 'TRIPLECLEAN', NULL, 1, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (272, 'À»“ŒÀ 350 Ï„', NULL, 10, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (273, 'Ã10√2   5À', NULL, 1, NULL, NULL, 2, 1, 1, 4, 8, 2, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (289, 'À” Œ…À  (5À)', NULL, 1, NULL, NULL, 2, 1, 1, 6, 5, 3, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (307, 'ƒŒ“-3', NULL, 2, NULL, NULL, 3, 1, 3, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (308, 'ƒŒ“-4  (455 „)', NULL, 2, NULL, NULL, 3, 1, 3, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (336, 'Ã10„2     (2.5À)', NULL, 1, NULL, NULL, 2, 1, 3, 4, 4, 2, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (338, 'Ã10√2    (2.5À)', NULL, 1, NULL, NULL, 2, 1, 3, 13, 4, 2, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (339, '¿¬“ŒÀ (–Œ«À»¬)', NULL, 1, NULL, NULL, 2, 1, 9, 3, 4, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (346, '‘»ŒÀ-2” (0,42 Í„)', NULL, 1, NULL, NULL, 2, 4, 4, 2, 4, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (348, 'ÿ–¡-4 (0,4 Í„)', NULL, 1, NULL, NULL, 2, 4, 6, 3, 4, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (350, '—ŒÀ»ƒŒÀ  (0,4Í„)', NULL, 1, NULL, NULL, 2, 4, 6, 2, 4, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (354, 'À” Œ…À  1À', NULL, 2, NULL, NULL, 2, 1, 4, 6, 5, 1, 3);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (357, 'À” Œ…À-—“¿Õƒ  (5À)', NULL, 1, NULL, NULL, 2, 1, 1, 6, 8, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (365, 'À»“ŒÀ (0.8)', NULL, 1, NULL, NULL, 2, 4, 3, 2, 5, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (366, 'À»“ŒÀ (0.4)', NULL, 1, NULL, NULL, 2, 4, 6, 2, 5, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (376, '–Œ—¿ 1À', NULL, 2, NULL, NULL, 3, 1, 2, 0, 0, 0, 0);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (377, 'Ã8¬    (4,5À)', NULL, 2, NULL, NULL, 2, 1, 7, 3, 4, 3, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (378, 'Ã6 14√1  (5À)', NULL, 2, NULL, NULL, 2, 1, 1, 16, 4, 1, 1);
INSERT INTO FUEL (CODFUEL, NAME, NUM, F_STOP, RATE, EXCISE, COD_G, COD_S, COD_1, COD_2, COD_3, COD_4, COD_5)
          VALUES (379, 'Ã6Á/12„   (4.5 Î)', NULL, 2, NULL, NULL, 2, 1, 7, 2, 9, 1, 1);

COMMIT WORK;
